<a href="https://colab.research.google.com/github/darialrsm/KSVD/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Лабораторна робота 1. Аналіз даних**

Завдання №1

In [2]:
import numpy as np

In [4]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Завдання №1 (2)

In [6]:
b = np.ones((4, 4), dtype=int)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Завдання №2

In [7]:
c = np.random.uniform(-1, 1, (5, 5))
c

array([[-0.00101285, -0.76167815, -0.47521662,  0.33810706, -0.70011018],
       [ 0.12132312,  0.76992516,  0.02127686,  0.63221607,  0.43935793],
       [-0.96273563, -0.69887696, -0.71720832,  0.85876501, -0.53539779],
       [ 0.34409389,  0.22442546,  0.52172663, -0.33215945, -0.61314613],
       [-0.76260607,  0.36090033,  0.82001014,  0.68458669,  0.20395423]])

Завдання №3

In [9]:
d = np.random.random((3, 3))
d

array([[0.38494843, 0.99397529, 0.00251114],
       [0.85653351, 0.85668959, 0.25234916],
       [0.31373677, 0.73224327, 0.09839891]])

Завдання №4

In [12]:
e1 = np.random.randint(1, 21, 6)
e2 = np.random.randint(1, 21, 6)
print(e1)
print(e2)
print(e1 + e2)
print(e1 - e2)
print(e1 * e2)

[ 9  5 13  7  4  9]
[ 7  1 18 10 11  7]
[16  6 31 17 15 16]
[ 2  4 -5 -3 -7  2]
[ 63   5 234  70  44  63]


Завдання №5

In [21]:
m1 = np.random.randint(1, 6, (3, 2))
m2 = np.random.randint(1, 6, (2, 4))
print("Матриця 1\n", m1)
print("Матриця 2\n", m2)
print("Результат\n", np.dot(m1, m2))

Матриця 1
 [[5 4]
 [1 5]
 [1 2]]
Матриця 2
 [[5 4 5 2]
 [1 3 5 1]]
Результат
 [[29 32 45 14]
 [10 19 30  7]
 [ 7 10 15  4]]


Завдання №6

In [24]:
m3 = np.random.rand(3, 3)
m4 = m3.T
print("Початкова матриця \n", m3)
print("Транспонована матриця \n",m4)

Початкова матриця 
 [[0.65839711 0.66415876 0.2197218 ]
 [0.76758574 0.13062563 0.45390578]
 [0.95215458 0.9908073  0.18908469]]
Транспонована матриця 
 [[0.65839711 0.76758574 0.95215458]
 [0.66415876 0.13062563 0.9908073 ]
 [0.2197218  0.45390578 0.18908469]]


Завдання №7

In [29]:
m5 = np.random.randint(1, 11, (3, 3))
m6 = np.random.randint(1, 11, (3, 3))
print("Матриця 1 \n", m5)
print("Матриця 2 \n", m6)
print("Різниця \n", m5 - m6)

Матриця 1 
 [[ 8  1 10]
 [ 2  3  4]
 [ 4  7  1]]
Матриця 2 
 [[4 9 5]
 [6 3 7]
 [1 4 5]]
Різниця 
 [[ 4 -8  5]
 [-4  0 -3]
 [ 3  3 -4]]


Завдання №8

In [35]:
m7 = np.random.randint(-5, 6, (3, 3))
m8 = np.random.randint(-5, 6, (3, 3))
print("Матриця 1 \n", m7)
print("Матриця 2 \n", m8)
print("Добуток \n", m7 * m8)

Матриця 1 
 [[ 2 -2 -1]
 [-4  5 -4]
 [-5 -5  4]]
Матриця 2 
 [[-4  3  4]
 [-2  5 -1]
 [-4  5  5]]
Добуток 
 [[ -8  -6  -4]
 [  8  25   4]
 [ 20 -25  20]]


Завдання №9

In [37]:
m9 = np.random.uniform(-1, 1, (3, 3))
sum = np.sum(m9, axis=1).reshape(-1, 1)
print(m9)
print("Сума елементів рядків \n", sum)

[[ 0.17169158 -0.14989625 -0.1585368 ]
 [-0.11803432 -0.81713854  0.68713864]
 [-0.67540223  0.58302854 -0.82164458]]
Сума елементів рядків 
 [[-0.13674147]
 [-0.24803422]
 [-0.91401828]]
